import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppBar } from "../components/AppBar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className= {inter.className}>
        <div className="w-full flex justify-center">
        <div className="w-[1440px] ">
        <AppBar />
        {children}
        </div></div>
      </body>
    </html>
  );
}
